### ISSUE TITLE
[Chiado] Deposits UI does only convert GNOs

### ISSUE THREAD

**Issue by giacomolicari** [gnosischain/issues#9] opened 2023-01-24 17:02 UTC
Deposits UI (https://deposit.gnosischain.com) is not completely depositing mGNO into the deposit contract, instead it just converts GNO into mGNO.

Sample transactions:
- not working deposit: https://blockscout.chiadochain.net/tx/0x3feb3f6d304fb905460168793829104e238ed98cca5f1e4dad241293cec18caf/logs
- working deposit: https://blockscout.chiadochain.net/tx/0x09c3df06257c2999bbbcf15ea6c2ffddc96f8211829a7995a2b614d509ff3518/logs

**Comment by filoozom** [comment] 2023-01-25 15:35
I haven't found the root cause yet (nor have I really looked for it), but right now the deposit UI only converts 1 GNO to 32 mGNO and that's it. The same actually happens with the [deposit CLI](https://github.com/gnosischain/deposit-contract/blob/develop/scripts/deposit.js), using the following configuration:
```
TOKEN_ADDRESS=0x19C653Da7c37c66208fbfbE8908A5051B57b4C70
WRAPPER_ADDRESS=0x917947dC7E341d843ab38e91623bcAeb65512b75
DEPOSIT_CONTRACT_ADDRESS=0xb97036A26259B7147018913bD58a774cf91acf25
START_BLOCK_NUMBER=155435
```

The "working deposit" transaction cited above is actually a bit different, and instead of doing the GNO -> mGNO conversion + depositing it only does the latter, which I was able to achieve with the deposit CLI using the following configuration:
```
META_TOKEN_ADDRESS=0xc5be8bf53755a41c2385e7aa86f6a9e28746f466
DEPOSIT_CONTRACT_ADDRESS=0xb97036A26259B7147018913bD58a774cf91acf25
START_BLOCK_NUMBER=155435
```
Resulting in the following transaction: https://blockscout.chiadochain.net/tx/0xb814f3c3140c580d220822b44c82cc3d7234ff9fbd70ee70203f445e4294017d. This of course assumes that the wallet already has 32 mGNO.

**Comment by alebanzas** [comment] 2023-01-31 17:54
I will close this issue. The potential paths are:

1. Get GNO and deposit, the tool will convert into mGNO without much interaction: https://deposit.gnosischain.com
2. From mGNO already (or convert manually GNO->mGNO) deposit: https://mgno.validategnosis.com/

**Closed as completed by alebanzas** 2023-01-31 17:54 UTC
Labels: bug, chain-infra
